# Generated by Django 4.1 on 2022-08-04 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Raid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('zone', models.CharField(blank=True, default='', max_length=100)),
                ('warcraftLogsId', models.CharField(blank=True, default='', max_length=100)),
                ('optional', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
