# Generated by Django 4.1 on 2022-08-04 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raids', '0002_alter_raid_options_alter_raid_id'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='raid',
            table='gxp_raids',
        ),
    ]
