# Generated by Django 4.1 on 2022-08-05 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raids', '0004_alter_raid_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raid',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
