# Generated by Django 4.1 on 2022-08-05 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raids', '0006_alter_raid_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Raider',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=12)),
                ('joinTimestamp', models.IntegerField()),
            ],
            options={
                'db_table': 'gxp_raiders',
            },
        ),
    ]
