# Generated by Django 4.1 on 2022-08-05 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raids', '0007_raider'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperienceEvent',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=260)),
                ('value', models.IntegerField()),
            ],
            options={
                'db_table': 'gxp_experience_events',
            },
        ),
    ]
