# Generated by Django 4.1 on 2022-08-05 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('raids', '0008_experienceevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alt',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=12)),
                ('raider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raids.raider')),
            ],
        ),
    ]
