# Generated by Django 4.1 on 2022-08-05 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raids', '0009_alt'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='alt',
            table='gxp_alts',
        ),
    ]
