# Generated by Django 4.1 on 2022-08-05 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raids', '0012_alter_alt_id_alter_experienceevent_id_alter_raid_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alt',
            old_name='raider',
            new_name='raiderId',
        ),
    ]
