# Generated by Django 4.1 on 2022-08-05 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raids', '0013_rename_raider_alt_raiderid'),
    ]

    operations = [
        migrations.AddField(
            model_name='raid',
            name='raiders',
            field=models.ManyToManyField(db_table='gxp_raids_raiders', related_name='raids', to='raids.raider'),
        ),
    ]
