# Generated by Django 4.1 on 2022-08-05 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raids', '0014_raid_raiders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raid',
            name='warcraftLogsId',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
