# Generated by Django 4.1 on 2022-08-05 18:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('raids', '0015_alter_raid_warcraftlogsid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raid',
            name='warcraftLogsId',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.CreateModel(
            name='ExperienceGains',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.IntegerField()),
                ('experienceEventId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experienceGains', to='raids.experienceevent')),
                ('raiderId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experienceGains', to='raids.raider')),
            ],
            options={
                'db_table': 'gxp_experience_gains',
            },
        ),
    ]
