class ExperienceEventKeys:
    COMPLETE_RAID_EVENT_ID = "COMPLETE_RAID"
    BOSS_KILL_EVENT_ID = "BOSS_KILL"
    MISSED_BOSS_KILL_EVENT_ID = "MISSED_BOSS_KILL"
    FOOD_ON_EVENT_ID = "BOSS_KILL_FOOD"
    FOOD_OFF_EVENT_ID = "BOSS_KILL_NO_FOOD"
    FLASK_ON_EVENT_ID = "BOSS_KILL_FLASK"
    FLASK_OFF_EVENT_ID = "BOSS_KILL_NO_FLASK"
    SIGNED_UP_ACCURATELY_EVENT_ID = "SIGNED_UP_ACCURATELY"
    SIGNED_UP_INACCURATELY_EVENT_ID = "SIGNED_UP_INACCURATELY"
    TOP_PERFORMER_EVENT_ID = "TOP_PERFORMANCE"
    HIGH_PERFORMER_EVENT_ID = "HIGH_PERFORMANCE"
    MID_PERFORMER_EVENT_ID = "MID_PERFORMANCE"
    LOW_PERFORMER_EVENT_ID = "LOW_PERFORMANCE"
    HEALER_TANK_LOW_PERFORMER_EVENT_ID = "HEALER_TANK_LOW_PERFORMANCE"
    DECAY_PER_BOSS_EVENT_ID = "DECAY_PER_BOSS"
    RESERVE_PER_BOSS_EVENT_ID = "RESERVE_PER_BOSS"
    PREVIOUS_EXPANSION_RAID_EVENT_ID = "PREV_EXPAC_RAID"


class BossKillZoneMultiplers:
    NAXXRAMAS = 1
    ULDUAR = 1.2
    TRIAL_OF_THE_CRUSADER = 1.1

    by_raid = {
        "Naxx / Sarth / Maly": NAXXRAMAS,
        "Ulduar": NAXXRAMAS,
        "TrIal of the Crusader": TRIAL_OF_THE_CRUSADER
    }