# Generated by Django 4.1 on 2022-08-05 21:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('raiders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperienceEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=260)),
                ('value', models.IntegerField()),
            ],
            options={
                'db_table': 'gxp_experience_events',
            },
        ),
        migrations.CreateModel(
            name='ExperienceGain',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.IntegerField()),
                ('experienceEventId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experienceGains', to='experience.experienceevent')),
                ('raiderId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experienceGains', to='raiders.raider')),
            ],
            options={
                'db_table': 'gxp_experience_gains',
            },
        ),
    ]
