# Generated by Django 4.1 on 2022-08-21 01:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("raiders", "0002_alter_raider_options_and_more"),
        ("raids", "0004_raid_encounters_completed"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExperienceEvent",
            fields=[
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("description", models.CharField(max_length=255)),
                ("template", models.CharField(max_length=255)),
                ("value", models.IntegerField()),
            ],
            options={
                "db_table": "gxp_experience_events",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="ExperienceLevel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("experience_required", models.IntegerField()),
            ],
            options={
                "db_table": "gxp_experience_levels",
                "ordering": ["experience_required"],
            },
        ),
        migrations.CreateModel(
            name="ExperienceGain",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("timestamp", models.IntegerField()),
                ("tokens", models.JSONField(default=dict)),
                ("value", models.IntegerField(null=True)),
                (
                    "experienceEvent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="experienceGains",
                        to="experience.experienceevent",
                    ),
                ),
                (
                    "raid",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="experienceGains",
                        to="raids.raid",
                    ),
                ),
                (
                    "raider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="experienceGains",
                        to="raiders.raider",
                    ),
                ),
            ],
            options={
                "db_table": "gxp_experience_gains",
                "ordering": ["timestamp"],
            },
        ),
    ]
