# Generated by Django 4.1 on 2022-08-21 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("experience", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="experiencegain",
            options={"ordering": ["timestamp"]},
        ),
        migrations.AlterModelOptions(
            name="experiencelevel",
            options={"ordering": ["experience_required"]},
        ),
    ]
