# Generated by Django 4.1 on 2022-08-22 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("experience", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="experienceevent",
            name="value",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="experiencegain",
            name="value",
            field=models.FloatField(null=True),
        ),
    ]
