# Generated by Django 4.1 on 2022-09-07 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("experience", "0002_alter_experienceevent_value_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="experienceevent",
            name="multiplied",
            field=models.BooleanField(default=True),
        ),
    ]
