# Generated by Django 4.1 on 2022-08-09 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0002_experienceevent_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experienceevent',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='experienceevent',
            name='key',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
