# Generated by Django 4.1 on 2022-08-09 13:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0003_alter_experienceevent_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperienceLevel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('experience_required', models.IntegerField()),
            ],
            options={
                'db_table': 'gxp_experience_levels',
                'ordering': ['experience_required'],
            },
        ),
    ]
