# Generated by Django 4.1 on 2022-08-09 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0004_experiencelevel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experiencelevel',
            options={'ordering': ['-experience_required']},
        ),
        migrations.AddField(
            model_name='experiencegain',
            name='tokens',
            field=models.JSONField(default={}),
        ),
    ]
