# Generated by Django 4.1 on 2022-08-09 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0005_alter_experiencelevel_options_experiencegain_tokens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiencegain',
            name='tokens',
            field=models.JSONField(default=dict),
        ),
    ]
