# Generated by Django 4.1 on 2022-08-11 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('raids', '0002_alter_raid_warcraftlogsid_alter_raid_zone'),
        ('experience', '0008_alter_experiencegain_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiencegain',
            name='raid',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='experienceGains', to='raids.raid'),
            preserve_default=False,
        ),
    ]
