# Generated by Django 4.1 on 2022-08-16 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('raids', '0006_alter_log_raidhelpereventid_alter_log_zone_and_more'),
        ('experience', '0009_experiencegain_raid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experienceevent',
            options={'ordering': ['key']},
        ),
        migrations.AlterField(
            model_name='experiencegain',
            name='raid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experienceGains', to='raids.raid'),
        ),
    ]
