# Generated by Django 4.1 on 2022-08-05 21:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('raiders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Raid',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.IntegerField()),
                ('zone', models.CharField(blank=True, default='', max_length=100)),
                ('warcraftLogsId', models.CharField(blank=True, default='', max_length=100)),
                ('optional', models.BooleanField(default=True)),
                ('raiders', models.ManyToManyField(db_table='gxp_raids_raiders', related_name='raids', to='raiders.raider')),
            ],
            options={
                'db_table': 'gxp_raids',
            },
        ),
    ]
