# Generated by Django 4.1 on 2022-08-09 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raids', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raid',
            name='warcraftLogsId',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='raid',
            name='zone',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
