# Generated by Django 4.1 on 2022-08-11 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raids', '0002_alter_raid_warcraftlogsid_alter_raid_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='raid',
            name='raidHelperEventId',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
