# Generated by Django 4.1 on 2022-08-14 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('raids', '0003_raid_raidhelpereventid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('logsCode', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False)),
                ('raidHelperEventId', models.CharField(blank=True, default='', max_length=255)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'gxp_logs',
            },
        ),
        migrations.RemoveField(
            model_name='raid',
            name='raidHelperEventId',
        ),
        migrations.RemoveField(
            model_name='raid',
            name='warcraftLogsId',
        ),
        migrations.AddField(
            model_name='raid',
            name='log',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='raid', to='raids.log'),
        ),
    ]
