# Generated by Django 4.1 on 2022-08-19 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("raids", "0003_alter_log_options_alter_raid_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="raid",
            name="encounters_completed",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
