# Generated by Django 4.1 on 2022-08-21 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("raids", "0004_raid_encounters_completed"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="raid",
            name="optional",
        ),
        migrations.AddField(
            model_name="log",
            name="optional",
            field=models.BooleanField(default=True),
        ),
    ]
