# Generated by Django 4.1 on 2022-08-14 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raids', '0004_log_remove_raid_raidhelpereventid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='timestamp',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='log',
            name='zone',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
