# Generated by Django 4.1 on 2022-08-16 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raids', '0005_log_timestamp_log_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='raidHelperEventId',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='zone',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='raid',
            name='zone',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
