# Generated by Django 4.1 on 2023-02-23 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("raiders", "0011_alter_specialistrole_raider"),
        ("raids", "0006_raid_optional"),
    ]

    operations = [
        migrations.AddField(
            model_name="raid",
            name="reserve_raiders",
            field=models.ManyToManyField(
                db_table="gxp_raids_reserve_raiders",
                related_name="reserve_raids",
                to="raiders.raider",
            ),
        ),
    ]
