# Generated by Django 4.1 on 2022-08-18 02:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Raider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=12)),
                ('joinTimestamp', models.IntegerField()),
            ],
            options={
                'db_table': 'gxp_raiders',
                'ordering': ['joinTimestamp'],
            },
        ),
        migrations.CreateModel(
            name='Alt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main', to='raiders.raider')),
                ('main', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alts', to='raiders.raider')),
            ],
            options={
                'db_table': 'gxp_alts',
                'ordering': ['main'],
            },
        ),
        migrations.CreateModel(
            name='Alias',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('raider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='raiders.raider')),
            ],
            options={
                'db_table': 'gxp_aliases',
                'ordering': ['raider'],
            },
        ),
    ]
