# Generated by Django 4.1 on 2022-08-05 21:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Raider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=12)),
                ('joinTimestamp', models.IntegerField()),
            ],
            options={
                'db_table': 'gxp_raiders',
            },
        ),
        migrations.CreateModel(
            name='Alt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=12)),
                ('raiderId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alts', to='raiders.raider')),
            ],
            options={
                'db_table': 'gxp_alts',
            },
        ),
    ]
