# Generated by Django 4.1 on 2022-08-18 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("raiders", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="raider",
            options={"ordering": ["join_timestamp"]},
        ),
        migrations.RenameField(
            model_name="raider",
            old_name="joinTimestamp",
            new_name="join_timestamp",
        ),
    ]
