# Generated by Django 4.1 on 2022-08-11 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('raiders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alt',
            old_name='raiderId',
            new_name='main',
        ),
        migrations.RemoveField(
            model_name='alt',
            name='name',
        ),
        migrations.AddField(
            model_name='alt',
            name='alt',
            field=models.ForeignKey(default='bf65cc97-b1b3-4f09-aeec-dcae3d1ebad7', on_delete=django.db.models.deletion.CASCADE, related_name='main', to='raiders.raider'),
            preserve_default=False,
        ),
    ]
