# Generated by Django 4.1 on 2022-08-21 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("raiders", "0002_alter_raider_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="raider",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
