# Generated by Django 4.1 on 2022-08-14 01:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('raiders', '0002_rename_raiderid_alt_main_remove_alt_name_alt_alt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alias',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('raider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='raiders.raider')),
            ],
            options={
                'db_table': 'gxp_aliases',
            },
        ),
    ]
