# Generated by Django 4.1 on 2022-08-16 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raiders', '0003_alias'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alias',
            options={'ordering': ['raider']},
        ),
        migrations.AlterModelOptions(
            name='alt',
            options={'ordering': ['main']},
        ),
        migrations.AlterModelOptions(
            name='raider',
            options={'ordering': ['joinTimestamp']},
        ),
    ]
