# Generated by Django 4.1 on 2022-08-22 13:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("raiders", "0003_raider_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="Rename",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("renamed_from", models.CharField(max_length=12)),
                (
                    "raider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="renames",
                        to="raiders.raider",
                    ),
                ),
            ],
            options={
                "db_table": "gxp_renames",
                "ordering": ["raider"],
            },
        ),
    ]
