# Generated by Django 4.1 on 2022-08-22 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("raiders", "0004_rename"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Alt",
        ),
    ]
