# Generated by Django 4.1 on 2022-08-22 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("raiders", "0005_delete_alt"),
    ]

    operations = [
        migrations.AddField(
            model_name="raider",
            name="main_raider",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="raiders.raider",
            ),
        ),
    ]
