# Generated by Django 4.1 on 2022-08-22 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("raiders", "0006_raider_main_raider"),
    ]

    operations = [
        migrations.RenameField(
            model_name="raider",
            old_name="main_raider",
            new_name="main",
        ),
    ]
