# Generated by Django 4.1 on 2022-08-23 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("raiders", "0007_rename_main_raider_raider_main"),
    ]

    operations = [
        migrations.AddField(
            model_name="raider",
            name="experience",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
