# Generated by Django 4.1 on 2022-08-23 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("raiders", "0008_raider_experience"),
    ]

    operations = [
        migrations.AlterField(
            model_name="raider",
            name="experience",
            field=models.FloatField(default=0),
        ),
    ]
