# Generated by Django 4.1 on 2023-02-20 21:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("raiders", "0009_alter_raider_experience"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpecialistRole",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("encounter", models.CharField(default="", max_length=255)),
                (
                    "raider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="raiders.raider"
                    ),
                ),
            ],
            options={
                "db_table": "gxp_specialist_roles",
            },
        ),
    ]
