# Generated by Django 4.1 on 2023-02-23 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("raiders", "0010_specialistrole"),
    ]

    operations = [
        migrations.AlterField(
            model_name="specialistrole",
            name="raider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="specialist_roles",
                to="raiders.raider",
            ),
        ),
    ]
